// The endpoint harness: artifact translation and one typed handle on
// `polymorph:iroh/endpoint@0.1.0` per endpoint instance.
//
// Everything here is host wiring; the exam scenarios in `run-endpoint.ts`
// (repo-internal) carry the verdicts. `bindEndpoint(...)` mirrors the jco
// host's retired `iroh.Endpoint.bind(...)` driving shape over
// `instantiate` + the polyengine embedder facade.
//
// MODULE-IDENTITY CONSTRAINT: this package instantiates the packaged endpoint
// component, so it still loads `@polyengine/runtime/embedder`; this
// package's `deno.json` and every consumer graph must resolve exactly one
// `@polyengine/runtime` version for stateful-handle interop. Vocabulary
// (`ComponentException`, etc.) comes from `@polyengine/protocol` (A22),
// whose copies are harmless even if a consumer resolves more than one.

import { defaultTranslator } from "@polyengine/translator";
import type { ComponentArtifacts } from "@polyengine/runtime/embedder";
import { instantiate } from "@polyengine/runtime/embedder";
import { ComponentException } from "@polyengine/protocol";
import { wasi } from "@polyengine/wasi";
import { webcryptoImports } from "@polymorph/webcrypto";
import { websocketImports } from "@polymorph/websocket";
import { webrtcImports } from "@polymorph/webrtc-datachannels";
import { socketsImports } from "./sockets.ts";
import type {
  BindConfig,
  Endpoint,
  IdentityGenerateExports,
  IrohEndpointExports,
} from "./types.ts";

export const IROH_ENDPOINT_INTERFACE = "polymorph:iroh/endpoint@0.1.0";
export const IDENTITY_GENERATE_INTERFACE = "polymorph:iroh/identity-generate@0.1.0";

// --- artifact ---------------------------------------------------------------

let cachedDefault: ComponentArtifacts | undefined;
let cachedExplicit: { bytes: Uint8Array; artifacts: ComponentArtifacts } | undefined;

export interface LoadArtifactsOptions {
  /**
   * Component bytes to translate instead of the packaged endpoint build.
   * Memoized by reference: passing the same array repeatedly translates
   * once.
   */
  readonly componentBytes?: Uint8Array;
}

async function translate(bytes: Uint8Array): Promise<ComponentArtifacts> {
  const translator = await defaultTranslator();
  const { plan, adapters } = translator.translate(bytes);
  return { plan, componentBytes: bytes, adapters };
}

/**
 * Translate the endpoint component once. The plan and adapters are reused
 * across every `instantiate` in the run: two endpoint *instances* are two
 * separate component instances over the same immutable artifacts.
 *
 * Without `componentBytes`, the packaged endpoint build is used. Its
 * module (`endpoint_component.ts`, generated by `just build-components`)
 * is reached through a string-literal dynamic import: the bytes ride the
 * statically-analyzable module graph — package integrity, no read
 * permission — but the multi-MiB module evaluates only when the packaged
 * default is actually used.
 *
 * The translator is `@polyengine/translator`'s packaged asset — the same
 * pinned release as the runtime, loaded through the module graph
 * (permission-free on Deno), so there is no fetch step and no
 * plan-format skew to guard against.
 */
export async function loadArtifacts(
  options: LoadArtifactsOptions = {},
): Promise<ComponentArtifacts> {
  const bytes = options.componentBytes;
  if (bytes !== undefined) {
    if (cachedExplicit?.bytes !== bytes) {
      cachedExplicit = { bytes, artifacts: await translate(bytes) };
    }
    return cachedExplicit.artifacts;
  }
  if (!cachedDefault) {
    const { endpointComponentBytes } = await import("./endpoint_component.ts");
    cachedDefault = await translate(endpointComponentBytes());
  }
  return cachedDefault;
}

// --- instances --------------------------------------------------------------

export interface EndpointInstanceOptions {
  /** Label used in log lines (`server`, `client`, …). */
  readonly label: string;
  /** Extra environment for the guest's `wasi:cli/environment`. */
  readonly env?: Record<string, string>;
  /** Component bytes to run instead of the packaged endpoint build. */
  readonly componentBytes?: Uint8Array;
}

export interface EndpointInstance {
  readonly label: string;
  readonly api: IrohEndpointExports;
  readonly identityGenerate: IdentityGenerateExports;
  /** Whatever the guest wrote to stdout/stderr through the WASI shims. */
  stdout(): string;
  stderr(): string;
}

/**
 * Stand up one component instance of the endpoint, with the sibling polyengine
 * host modules supplying every non-WASI import.
 *
 * Import fragments are built FRESH per instance: the host modules' resource
 * classes carry per-instance registry identity, and sharing one record
 * across two instantiations would alias two guests onto one table.
 */
export async function newEndpointInstance(
  options: EndpointInstanceOptions,
): Promise<EndpointInstance> {
  const artifacts = await loadArtifacts({ componentBytes: options.componentBytes });
  const shims = wasi({
    cli: {
      args: [`iroh-endpoint-${options.label}`],
      env: { ...options.env },
    },
  });
  const imports = {
    ...shims,
    ...webcryptoImports(),
    ...websocketImports(),
    ...webrtcImports(),
    ...socketsImports(),
  };
  const instance = await instantiate(artifacts, imports);
  const api = instance.exports[IROH_ENDPOINT_INTERFACE] as IrohEndpointExports;
  const identityGenerate = instance
    .exports[IDENTITY_GENERATE_INTERFACE] as IdentityGenerateExports;
  if (!api || typeof api.Endpoint?.bind !== "function") {
    throw new Error(
      `export "${IROH_ENDPOINT_INTERFACE}" missing or shapeless; plan exports: ` +
        artifacts.plan.exports.map((e: { name: string }) => e.name).join(", "),
    );
  }
  if (typeof identityGenerate?.generate !== "function") {
    throw new Error(`export "${IDENTITY_GENERATE_INTERFACE}" missing or shapeless`);
  }
  return {
    label: options.label,
    api,
    identityGenerate,
    stdout: () => shims.captured.stdoutText(),
    stderr: () => shims.captured.stderrText(),
  };
}

/**
 * `Endpoint.bind`, with the retired jco host's driving shape: generate
 * an identity, construct `endpoint-options` around it, populate the
 * setters, bind. The options resource is consumed by `bind`; the
 * identity's borrow ends at the constructor, so it is dropped once the
 * endpoint is up.
 */
export async function bindEndpoint(
  instance: EndpointInstance,
  config: BindConfig,
): Promise<Endpoint> {
  const identity = await instance.identityGenerate.generate();
  const options = new instance.api.EndpointOptions(identity);
  for (const alpn of config.alpns) await options.addAlpn(alpn);
  if (config.relayUrl !== undefined) await options.relayUrl(config.relayUrl);
  if (config.udpBindAddr !== undefined) await options.udpBindAddr(config.udpBindAddr);
  if (config.webrtc) await options.webrtc(true);
  const endpoint = await instance.api.Endpoint.bind(options);
  identity.drop();
  return endpoint;
}

// --- small helpers ----------------------------------------------------------

export const hex = (bytes: Uint8Array): string =>
  Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");

/** Endpoint ids are 64 hex chars; log them short (they are public keys). */
export const shortId = (bytes: Uint8Array): string => `${hex(bytes).slice(0, 12)}…`;

export const utf8: TextEncoder = new TextEncoder();
export const fromUtf8: TextDecoder = new TextDecoder();

/** Reject after `ms`, so a wedged scenario names itself instead of hanging. */
export function deadline<T>(promise: Promise<T>, ms: number, what: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const bomb = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error(`timed out after ${ms} ms: ${what}`)), ms);
  });
  return Promise.race([promise, bomb]).finally(() => {
    if (timer !== undefined) clearTimeout(timer);
  }) as Promise<T>;
}

/** Render a rejection, unwrapping the branded WIT error payload. */
export function describeError(err: unknown): string {
  if (err instanceof ComponentException) {
    const p = err.payload as { kind?: string; value?: unknown } | undefined;
    return `ComponentException ${p?.kind ?? "?"}${p?.value === undefined ? "" : `(${String(p.value)})`}`;
  }
  return err instanceof Error ? `${err.name}: ${err.message}` : String(err);
}
