// Embed the built endpoint component as @polymorph/iroh's asset module:
//
//   target/wasm32-wasip2/release/iroh_endpoint.wasm
//     -> host-polyengine/src/endpoint_component.ts   (gitignored, GENERATED)
//
// Run by `just build-components` and by the jsr-publish workflow. Base64
// in a TypeScript module keeps the bytes inside the statically-analyzable
// module graph — JSR package integrity, no read permission, no bundler
// special-casing — where a raw-bytes import would need Deno's unstable
// raw-imports flag.
//
//   deno run --allow-read=target \
//     --allow-write=host-polyengine/src/endpoint_component.ts \
//     scripts/embed-endpoint-component.ts

const WASM = "target/wasm32-wasip2/release/iroh_endpoint.wasm";
const OUT = "host-polyengine/src/endpoint_component.ts";

const wasm = await Deno.readFile(WASM);
let bin = "";
const CHUNK = 0x8000;
for (let i = 0; i < wasm.length; i += CHUNK) {
  bin += String.fromCharCode(...wasm.subarray(i, i + CHUNK));
}
const b64 = btoa(bin);

const out = `// deno-fmt-ignore-file
// GENERATED by scripts/embed-endpoint-component.ts (\`just build-components\`)
// — do not edit. The iroh endpoint component (wasm32-wasip2, release),
// base64-embedded so the bytes ride the module graph: package integrity,
// no read permission, no unstable raw-import flag. Reached only through
// loadArtifacts()'s string-literal dynamic import, so this module
// evaluates only when the packaged default is used.

const B64 = "${b64}";

/** The packaged endpoint component's bytes (decoded per call). */
export function endpointComponentBytes(): Uint8Array {
  const bin = atob(B64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}
`;
await Deno.writeTextFile(OUT, out);
console.log(`embedded ${wasm.length} bytes -> ${OUT}`);
